### ISSUE TITLE
建议增加一个ComboGrid控件

### ISSUE THREAD

**Issue by shengzhijie** [kwwwvagaa/NetWinformControl#1]
![image](https://user-images.githubusercontent.com/12422953/63819342-90d9e100-c977-11e9-8dff-2d9768e52c5f.png)
建议增加一个类似于easyui的ComboGrid控件，可以显示多列，支持录入检索的功能，这个控件很实用，另外建议优化日期时间选择控件，使用感觉有点卡顿

**Comment by kwwwvagaa** [comment]
已经增加了。谢谢你的建议

**Comment by coflery** [comment]
nice

**Comment by Zhang123Ashan** [comment]
666，被惊艳到了
