### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by dathlin** [kwwwvagaa/NetWinformControl#13]
兄弟，是不是代码有点侵权了？没有提前和我联系呢
https://github.com/dathlin/HslControlsDemo

**Comment by kwwwvagaa** [comment]
请联系我QQ623128629，谢谢

**Comment by dathlin** [comment]
加你了


| |
Chasing
|
|
hsl200909@163.com
|
签名由网易邮箱大师定制
在2019年10月29日 09:22，kwwwvagaa<notifications@github.com> 写道：

请联系我QQ623128629，谢谢

**Comment by kwwwvagaa** [comment]
QQ 并没有收到好友请求，你的qq禁止添加，相关的使用给你报表的功能已经全部删除了
