### ISSUE TITLE
Combobox items dual screen

### ISSUE THREAD

**Issue by YuqseLx** [kwwwvagaa/NetWinformControl#23]
Hello, thank you for good controls.
But i need help for issue in dual screen.
When main form at secondary screen combobox items showing first screen.

**Comment by kwwwvagaa** [comment]
You can modify the source code to implement it by yourself for the time being, and you will fix the problem of multi screen later.

The modification idea is as follows: judge the screen of the current control when it pops up, and set the pop-up window to the current screen when it pops up.

**Comment by YuqseLx** [comment]
Thank you when i use that again, i will impelement :)
