### ISSUE TITLE
step控件显示不正常

### ISSUE THREAD

**Issue by anxidongri** [kwwwvagaa/NetWinformControl#4]
当step的显示名字长一点的时候，会导致后面的step显示不了或者不完整。
比如把现在的step1/step2/step3改成step1asdfsafaafasfsdfsdf，就会导致后面完全不显示了。

**Comment by kwwwvagaa** [comment]
谢谢反馈

**Comment by kwwwvagaa** [comment]
bug已经解决了，谢谢反馈
